/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testBitTransformBlackWhite() {
        Bitmap test = new Bitmap("./src/assets/mario.bmp", "./src/assets/", "blackWhite-images.bmp");
        assertNull("The output is correct ", test.blackWhite());
    }

    @Test public void testBitTransformBluifyBlue() {
        Bitmap test = new Bitmap("./src/assets/mario.bmp", "./src/assets/", "bluifyBlue-images.bmp");
        assertNull("The output is correct ", test.bluifyBlue());
    }
    @Test public void testBitTransformBluifyGreen() {
        Bitmap test = new Bitmap("./src/assets/mario.bmp", "./src/assets/", "bluifyGreen-images.bmp");
        assertNull("The output is correct ", test.bluifyGreen());
    }
    @Test public void testRitTransformBluifyRed() {
        Bitmap test = new Bitmap("./src/assets/mario.bmp", "./src/assets/", "bluifyRed-images.bmp");
        assertNull("The output is correct ", test.bluifyRed());
    }
    @Test public void testMirror() {
        Bitmap test = new Bitmap("./src/assets/mario.bmp", "./src/assets/", "mirror-images.bmp");
        assertNull("The output is correct ", test.mirror());
    }
}
