/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;

public class App {


    public static void main(String[] args) {
        Bitmap  test = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "mirror-images.bmp");
        test.mirror();

        Bitmap  test2 = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "blackWhite-images.bmp");
        test2.blackWhite();

        Bitmap  test3 = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "bluifyBlue-images.bmp");
        test3.bluifyBlue();

        Bitmap  test4 = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "bluifyRed-images.bmp");
        test4.bluifyRed();

        Bitmap  test5 = new Bitmap("./app/src/assets/mario.bmp", "./app/src/assets/", "bluifyGreen-images.bmp");
        test5.bluifyGreen();



    }




}
